<a href="https://colab.research.google.com/github/bengaldr0gon/2024-intro-DA-code/blob/main/CHAPTER_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# *SECTION 01*

## 자료형 ndarray

### 다차원 배열 ndarray

In [ ]:
import numpy as np # numpy를 np로 별칭해서 사용

a = np.ndarray(shape=(2,2), dtype=int)# 2행 2열 모양의 int타입으로 채워진 배열을 생성한다.
a # 출력되는 배열안에있는 값은 초기화 되지않은 임의의 메모리값.

array([[102333809023375,               0],
       [135112888991088, 135112888127344]])

### 내장함수 array()로 ndarray 생성

In [ ]:
a = np.array([1, 2, 3], dtype = int) # [1, 2, 3]으로 1차원 배열 생성
a

array([1, 2, 3])

In [ ]:
type(a) # a 의 타입은 다차원 배열에 속해있으므로 ndarray 이다.

numpy.ndarray

In [ ]:
print(a.shape) # 배열 a의 요소는 3개, 차원은 1차원이다.
print(a.ndim) # ndim은 차원 수를 의미한다.
print(a.dtype) # 배열 요소의 데이터 형식을의미한다.
print(a.itemsize) # 배열의 각 요소의 크기(바이트)를 의미한다.
print(a.nbytes) # 배열의 전체 크기(바이트)를 의미한다.
print(a.data) # 배열 요소를 실제로 포함하고 있는 버퍼의 시작 위치를 의미한다.

(3,)
1
int64
8
24


In [ ]:
np.array(1, 2, 3) # 함수 array의 인자는 배열을 표현하는 리스트나 튜플 하나이다. 이 이외에는 오류가 발생함.

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [ ]:
np.array([1, 'py', 3.14]) # ndarray는 모든 항목이 단일한(쉽게말해 통일된) 자료형으로 구성된다, 이것과 같이 항목이 하나라도 문자열이면 모든항목이 문자열 자료형 U32로 저장됨.
# U32자료형은 유니코드 문자열 자료형을 나타낸다.

array(['1', 'py', '3.14'], dtype='<U32')

In [ ]:
unicode_array = np.array(['가나다', '라마바', '사아자'], dtype='<U32') #
unicode_array

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [ ]:
lang = np.array(['파이썬', '자바', '씨']) # dtype은 굳이 적지않아도 출력됨.
lang

array(['파이썬', '자바', '씨'], dtype='<U3')

In [ ]:
lang = np.array(['파이썬', '자바', '씨'], dtype = str) #
lang

array(['파이썬', '자바', '씨'], dtype='<U3')

In [ ]:
a = np.array((1, 2, 3,), dtype = float) # dtype = float으로 명시하면 모든 항목의 자료형이 float가 된다.
a

array([1., 2., 3.])

In [ ]:
b = np.array((1, 2.5, 3)) # 하지만 dtype = float가 없더라도 배열 원소 중 하나라도 flaot일 경우 자동으로 더 큰 범주인 flaot가 dtype이 된다.
b

array([1. , 2.5, 3. ])

# *SECTION 02*

## 내장함수 arrange()

### numpy의 내장함수 arange() 활용

In [ ]:
import numpy as np
# arange()는 파이썬의 내장함수 range()와 매우 유사하다,
print(np.arange(3))
print(np.arange(3, 7))
print(np.arange(3, 7, 2))
# numpy.arange()로 출력된 결과는 인자에 콤마가 없다.

[0 1 2]
[3 4 5 6]
[3 5]


In [ ]:
print(np.arange(2.0)) #실수의 배열도 출력가능하다.
print(np.arange(2.0, 6.5)) # 끝값이 1로 딱 나누어 지지않더라도 기본적인 step은 1로 지정되어있음.
print(np.arange(2.0, 6.5, 0.8)) # step은 변경가능.

[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


### 배열의 모양을 바꾸는 reshape()

In [ ]:
a = np.arange(12).reshape(3, 4) # 0~11 까지의 배열을 3행 4열 형태로 출력한다. 이때 행 * 열 = (arange의 end값)이 되는게 정상.
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.reshape(a, (2, 6)) # 2 * 6 = 12 로 출력가능하다. 2행 6열의 배열을 출력한다.

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
np.reshape(a, (3, 5)) # 3 * 5 = 15 로 오류가 발생한다.

ValueError: cannot reshape array of size 12 into shape (3,5)

In [ ]:
b = np.array([1, 2, 3, 4, 5, 6]).reshape(3, 2) # 1~6까지의 배열을 3행 2열로 출력한다.
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.reshape(b, (2, -1)) # 행 또는 열에 -1을 지정하면 명시하지않아도 원소 수와 열 또는 행 수에 맞게 지정해 달라는 의미이다.

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.reshape(b, (-1,-1)) # 둘다 -1로 지정하면 오류 발생.

ValueError: can only specify one unknown dimension

## 내장함수 linspace()

### 내장함수 linspace() 활용

In [ ]:
import numpy as np
np.linspace(2.0, 3.0) #[2,3]구간에서 "3을 포함해" 인자 num의 기본값인 50개의 수로 등분하는 수의 배열을 반환한다.

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [ ]:
np.linspace(2.0, 3.0, retstep=True) # retstep=True로 등분 간격을 반환할 수 있다. *retstep은 return step의 약자.

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [ ]:
np.linspace(2.0, 3.0, retstep=False) # 기본값은 False임.

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [ ]:
print( (3-2) / (50-1)) #  직접 계산하면 다음과 같다.

0.02040816326530612


In [ ]:
np.linspace(2.0, 3.0, endpoint=False, retstep=True) #endpoint = false는 마지막 숫자를 제외하고 50개의 수로 등분한다.

(array([2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18, 2.2 ,
        2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 , 2.42,
        2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62, 2.64,
        2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84, 2.86,
        2.88, 2.9 , 2.92, 2.94, 2.96, 2.98]),
 0.02)

In [ ]:
print( (3-2) / 50 ) # 마지막 수 3이 빠졌으므로 -1을 하지않는다고 생각하면 편함.

0.02


In [ ]:
np.linspace(2.0, 3.0, num=5, retstep=True) # num=n을 통해 n등분한다. n등분 = 인자의 수

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [ ]:
print( (3-2)/ (5-1))

0.25


In [ ]:
np.linspace(2.0, 3.0, num=5, endpoint=False, retstep=True)

(array([2. , 2.2, 2.4, 2.6, 2.8]), 0.2)

In [ ]:
print( (3-2)/ 5)

0.2


### 내장함수 arange()와 linspace() 비교

In [ ]:
np.arange(0.1, 0.4, 0.1) # float의 부정확성때문에 발생한다. 정상적인경우 [0.1, 0.2, 0.3] 으로 출력됨.

array([0.1, 0.2, 0.3, 0.4])

In [ ]:
np.arange(1, 4, 1) / 10.0 #정수로 계산해서 10으로 나누는 방법

array([0.1, 0.2, 0.3])

In [ ]:
np.linspace(0.1, 0.4, 3, endpoint=False)

array([0.1, 0.2, 0.3])

In [ ]:
np.linspace(0.1, 0.4, 4)

array([0.1, 0.2, 0.3, 0.4])

# *SECTION 03*

## 내장함수 zeros()와 ones()

### 원소가 모두 0인 배열을 생성하는 zeros()

In [ ]:
import numpy as np

a = np.zeros(5) # np.zeros()는 주어지는 shape 형태로 0이 채워진 ndarray를 반환하는 함수이다.
a

array([0., 0., 0., 0., 0.])

In [ ]:
a.dtype

dtype('float64')

In [ ]:
np.zeros((5,), dtype=int) # 0으로 채운 5개의 요소의 1차원 배열을 생성

array([0, 0, 0, 0, 0])

In [ ]:
b = np.zeros((2, 1))# 인자가 0인 요소가 2개인 2차원 배열을 생성한다.
b

array([[0.],
       [0.]])

In [ ]:
b.shape

(2, 1)

### 원소가 모두 1인 배열을 생성하는 ones()

In [ ]:
import numpy as np

np.ones((2, 4)) # zeros()와 비슷한 원리로 0이 아닌 1로 채운다. 마찬가지로 기본타입은 float

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones((2, 4), dtype = int) # dtype을 int로 지정하면 원소가 정수로 변환된다.

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

## 내장함수 eye()와 full(), empty()

### 대각선 원소가 모두 1인 2차원 배열을 생성하는 eye()

In [ ]:
import numpy as np

np.eye(3) #eye(n)은 n행 n열의 2차원 배열을 반환한다. 반환되는 2차원 배열의 대각선은 모두 1이다. 이 또한 zero,ones와 동일하게 기본 type은 float

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(2, dtype=int) # 마찬가지로 타입 변경은 가능하다.

array([[1, 0],
       [0, 1]])

In [ ]:
np.eye(3, 4) # eye(m, n) 호출은 m행과 n열의 2차원 배열을 반환하면서 반환하는 2차원 배열에서 첨자 (0,0)으로 시작되는 대각선은 모두 1.0이다.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
a = np.eye(3, 4, 1) #eye(m, n, k) 호출에서 대각선의 위치를 k로 수정할 수 있다. +k는 대각선을 k만큼 오른쪽(위)로 평행이동.
a

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
a = np.eye(3, 4, -1) # -k는 대각선을 k만큼 왼쪽(아래)로 평행이동한다.
a

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

### 원소가 모두 1인 배열을 생성하는 full()

In [ ]:
import numpy as np

np.full([2, 3], 10) # 함수 full(shape, fill_value)는 fill_value로 shape모양의 배열을 반환하는 함수이다.

array([[10, 10, 10],
       [10, 10, 10]])

In [ ]:
np.full([2, 3], (1, 2, 3))# [1, 2, 3]을 2행 3열로 출력함.

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
np.full([3, 4], (0, 1, 2, 3)) # [0, 1, 2, 3]을 3행 4열로 출력함.

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [ ]:
np.full([4, 3], fill_value = np.arange(4).reshape(4, 1)) # 0~3까지 4행 1열로 출력하고(2차원) 이걸 또 4행 3열로 출력한다.

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

### 원소가 모두 1인 배열을 생성하는 empty()

In [ ]:
import numpy as np

np.empty([2, 2]) # 2행 2열의 예측할 수 없는 원소값으로 채워진 2차원 배열을 출력한다,

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [ ]:
np.empty(3) # 3개의 원소값

array([4.9e-324, 9.9e-324, 1.5e-323])

In [ ]:
np.empty([2, 3], dtype = int) # 정수인 2행 3열 2차원 배열을 생성한다.

array([[4607182418800017408, 4607182418800017408, 4607182418800017408],
       [4616189618054758400, 4612811918334230528, 4611686018427387904]])

## 내장함수 zeros_like()와 ones_like(), full_like()

### 원소값이 0인 주어진 형태의 배열을 생성하는 zeros_like()

In [ ]:
import numpy as np

a = np.arange(8).reshape(2, 4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
np.zeros_like(a) # 함수 zeros_like(a)는 인자 a "형태"의 배열로 원소 값은 모두 0인 배열을 반환한다.

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

### 원소값이 1인 주어진 형태의 배열을 생성하는 ones_like()

In [ ]:
np.ones_like(a) # 함수 ones_like(a)는 인자 a "형태"의 배열ㄹ로 원소 값은 모두 1인 배열을 반환한다.

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.full_like(a, 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

# *SECTION 04*

## 배열 기본 연산

### 배열과 스칼라의 연산

In [ ]:
import numpy as np

a = np.arange(3)
a

array([0, 1, 2])

In [ ]:
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)
#다음과 같이 모든 원소에 연산을 수행한 같은 모양의 배열을 반환한다.

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


### 배열과 배열의 연산

In [ ]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b = np.full_like(a, [1, 2, 3]) # 2행 3열의 형태로 배치
b

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)
#모양이 같은 두 배열의 사칙 연산도 같은 위치의 원소끼리 연산이 수행된 같은 모양의 배열이 반환된다.

[[2 4 6]
 [5 7 9]]
[[0 0 0]
 [3 3 3]]
[[ 1  4  9]
 [ 4 10 18]]
[[1.  1.  1. ]
 [4.  2.5 2. ]]


In [ ]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
b = np.arange(0.5, 4, 1)
b

array([0.5, 1.5, 2.5, 3.5])

In [ ]:
a += b # 결과값은 float인데 a원소 자료형은 int 이므로 오류가 발생한다.

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [ ]:
b += a
b

array([0.5, 2.5, 4.5, 6.5])

In [ ]:
a = np.full((2, 3), [1, 2, 3])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
b = np.full((3, 2), [2, 1])
b

array([[2, 1],
       [2, 1],
       [2, 1]])

In [ ]:
a @ b # a @ b는 앞 배열의 "열"과 뒤 배열의 "행"이 같아야 수행할 수 있다.

array([[12,  6],
       [12,  6]])

In [ ]:
a.dot(b)

array([[12,  6],
       [12,  6]])

In [ ]:
b.dot(a) # 일반적으로 배열의 곱은 교환법칙이 성립하지않는데 위의 a의 shape는 (2,3), b는 (3,2)이므로 b @ a 도 성립한다.

array([[3, 6, 9],
       [3, 6, 9],
       [3, 6, 9]])

## 배열 함수와 범용 함수

### 배열 함수

In [ ]:
a = np.array([[10, 20], [5, 8], [1, 2]])
a

array([[10, 20],
       [ 5,  8],
       [ 1,  2]])

In [ ]:
a.sum() # a.sum()은 배열의 모든 원소 합이 반환된다.

46

In [ ]:
a.sum(axis=0) # a.sum(axis = 0)은 동일열에서 세로로 더한 값을 구한 배열을 반환한다.

array([16, 30])

In [ ]:
a.sum(axis=1) # a.sum(axis = 1)은 동일행에서 가로로 더한 값을 구한 배열을 반환한다,

array([30, 13,  3])

In [ ]:
print(np.sum(a))
print(np.sum(a, axis=0))
print(np.sum(a, axis=1))
#다음과 같이도 출력가능함

46
[16 30]
[30 13  3]


In [ ]:
a = np.array([[3, 5, 8], [1, 2, 3]])
a

array([[3, 5, 8],
       [1, 2, 3]])

In [ ]:
a.cumsum() # ndarray.cumsum()은 모든 원소를 순서대로 누적 합계를 반환한다. *n차원도 1차원 배열이 된다.

array([ 3,  8, 16, 17, 19, 22])

In [ ]:
a.cumsum(axis=0) # 다음과 같이 동일 열에서의 누적 합계도 구할 수 있다. *n차원은 동일한 배열 모양의 결과

array([[ 3,  5,  8],
       [ 4,  7, 11]])

In [ ]:
a.cumsum(axis=1) # 동일 행에서의 누적 합계도 구할 수 있음 *n차원은 동일한 배열 모양의 결과

array([[ 3,  8, 16],
       [ 1,  3,  6]])

### 범용 함수

In [ ]:
import numpy as np

a  = np.array([1, 4, 9])
np.sqrt(a) # 요소별 제곱근을 배열로 반환한다. 데이터타입은 float

array([1., 2., 3.])

In [ ]:
np.log(a) # 요소별 자연 로그 함수가 적용된 값을 반환한다.

array([0.        , 1.38629436, 2.19722458])

In [ ]:
a = np.array([1, 4, 9])
a

array([1, 4, 9])

In [ ]:
b = np.full_like(a, 2)
b

array([2, 2, 2])

In [ ]:
np.add(a, b) # 요소별 덧셈

array([ 3,  6, 11])

In [ ]:
np.divide(a, b) # 요소별 나눗셈

array([0.5, 2. , 4.5])

In [ ]:
np.power(a, b) # 요소별 제곱

array([ 1, 16, 81])

# *SECTION 05*

## 배열 첨자와 슬라이싱

### 1차원 배열의 첨자와 슬라이싱

In [3]:
import numpy as np

a = np.power(np.arange(10), 2) #1~9까지 제곱한 원소로 구성된 1차원 배열 a를 반환한다.
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [4]:
print(a[3])
print(a[-2])
# 정수 첨자는 0부터 시작 가능하며, 끝부터는 -1로 시작되는 음수로도 참조 가능하다.

9
64


In [5]:
print(a[1:4]) # [start:stop]의 슬라이싱으로 start 부터 stop-1 까지의 부분 배열이 반환된다
print(a[-5 : -1])

[1 4 9]
[25 36 49 64]


In [6]:
print(a[8:2:-1]) # start>step일 경우 step이 -로 지정되지 않으면 아무것도 출력되지 않는 빈 배열이 반환된다.
print(a[-1:-7:-1])

[64 49 36 25 16  9]
[81 64 49 36 25 16]


In [7]:
a[::-1] #역순의 배열을 출력한다

array([81, 64, 49, 36, 25, 16,  9,  4,  1,  0])

In [8]:
a[::-2]

array([81, 49, 25,  9,  1])

In [9]:
a[2:5] = -100 # a[2~4]에 모두 -100이 대입됨
a

array([   0,    1, -100, -100, -100,   25,   36,   49,   64,   81])

In [10]:
a[2:5] = [-5, -5, -5] # 값이 아닌 모양이 같은 배열을 대입해도 가능하다.

In [11]:
a[2:5] = [-5, -5] # 다음처럼 2개 원소의 배열을 대입하면 오류가 발생함

ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [14]:
b = np.array([5] * 10) #곱 연산자로 생성한 배열
b

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [15]:
b[::2] = -10 # 0,2,4,6,8 즉 2간격씩 값을 저장
b

array([-10,   5, -10,   5, -10,   5, -10,   5, -10,   5])

In [16]:
b[::2] = np.arange(5) # 2간격 씩 0~4까지 차례로 저장
b

array([0, 5, 1, 5, 2, 5, 3, 5, 4, 5])

### 2차원 배열의 첨자와 슬라이싱

In [17]:
a = np.arange(30).reshape(5, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [18]:
a[3] #2차원 배열에서 a[i]는 첨자 i인 1차원 행 배열이다,

array([18, 19, 20, 21, 22, 23])

In [19]:
a[-1] #첨자는 음수도 가능하며 첨자 -1은 마지막 첨자이다.

array([24, 25, 26, 27, 28, 29])

In [20]:
a[-2, :] # 2차원 배열에서 두번째 첨자에 :는 생략해도 무방하다.

array([18, 19, 20, 21, 22, 23])

In [21]:
a[2:4] # 2행과 3행을 2차원 배열로 출력한다.

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [22]:
a[1:5:2]# 1행과 3행을 2차원 배열로 출력한다.

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [23]:
a[:, 1] # 모든 행에 대해 열의 첨자 1인 "1차원" 배열이 반환된다.

array([ 1,  7, 13, 19, 25])

In [24]:
a[:, 1:6] # 1에서 5까지의 2차원 배열이 반환된다.

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [25]:
a[:, ::2] # 열 첨자 0, 2, 4로 출력된 배열이 반환된다.

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [26]:
a[2, 4] # a[i, j]는 좌표지정과 같은 역할을 하며, 스칼라값을 반환한다.

16

In [27]:
a[2][4] # a[i, j]와 같다

16

In [28]:
a[1:3, 2:5] # 1,2행, 2,3,4열에 모두 해당하는 인자들로 배열이 반환된다.

array([[ 8,  9, 10],
       [14, 15, 16]])

In [29]:
a[:, :] #전체 배열 반환

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [30]:
a[::-1, ::-1] # 원 배열 a의 행과 열이 모두 바뀐 배열이 반환된다.

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

### 3차원 배열의 첨자와 슬라이싱

In [31]:
a  = np.arange(24).reshape(2, 3, 4) # 3차원 배열은 2차원 배열이 n개 존재한다고 생각하면 된다. 다음의 배열은 3행 4열의 배열이 2개 존재한다.
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [32]:
a[1] # a[1] 은 axis = 0은 첨자 1로 두번째 (3, 4) 배열이다.

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [33]:
a[:, 1] # axis=0의 범위에 해당하는 깊이에서 행의 첨자가 1인 배열을 반환한다.

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [34]:
a[:, 1, 1] # 위의 첨자가 1인 배열에서 열의 첨자가 1인 (1, 2) 모양 2차원 배열이 반환된다.

array([ 5, 17])

In [35]:
a[:, : , 1] # 3차원 배열 a에서 axis=2의 첨자가 1인 (2,3)모양의 2차원 배열을 반환한다.

array([[ 1,  5,  9],
       [13, 17, 21]])

In [36]:
a[...,1] #...은 해당되는 축이 모두 :인 것을 의미한다. = a[:,:,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [37]:
a[1, ..., 1] # = a[1,:,1]

array([13, 17, 21])

In [38]:
a[0,...] # = a[0,:,:], a[0] / a[0]은 axis=0에서 첨자 0인 2차원 배열을 의미한다.

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 배열 형태 수정

### 1차원 배열로 만드는 ndarray.ravel()

In [40]:
a = np.arange(12).reshape(2, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [41]:
a.ravel() # 1차원 배열로 만들어버림!

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### np.transpose(a)와 a.transpose(), a.T

In [42]:
a = np.arange(1,7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
np.transpose(a) # 같은행은 열이 되고 같은 열은 행이 된다.

array([[1, 4],
       [2, 5],
       [3, 6]])

In [44]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [45]:
a.T
#이러한 3가지 방법으로 반환 가능함.

array([[1, 4],
       [2, 5],
       [3, 6]])

In [46]:
np.transpose(a, (0, 1)) # (0, 1)은 원래의 행렬이 그대로 출력된다. / 현재의 경우 a가 2차원 배열이기에 (0,1), (1,0) 2가지 경우밖에 존재하지않지만 3차원 배열의 경우 전치 행렬의 방법이 매우 다양하다.

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
np.transpose(a, (1, 0)) # (1, 0)은 전치 행렬이 반환된다. *전치: 주어진 행렬의 행 과 열을 바꾼 행렬을 의미한다.

array([[1, 4],
       [2, 5],
       [3, 6]])

In [48]:
b = np.arange(1, 13).reshape(3, 2, 2)
b

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [49]:
b.T # 3차원에서의 기본적인 전치 방법은 a(j, i, k) -> a(k, j , i)가 된다. 깊이 -> 행/ 행 -> 열/열 -> 깊이

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [50]:
np.transpose(b, (0, 1, 2)) # 3차원 행렬 b를 그대로 출력한다.

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [51]:
np.transpose(b, (2, 1, 0)) # 깊이와 열을 바꿔서 출력한다.

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [52]:
np.transpose(b, (0, 2, 1)) # 1축과 2축을 서로 바꾼 전치 행렬

array([[[ 1,  3],
        [ 2,  4]],

       [[ 5,  7],
        [ 6,  8]],

       [[ 9, 11],
        [10, 12]]])

In [53]:
c  = np.arange(1, 13).reshape(2, 2, 3) #깊이2, 행2, 열3인 배열을 생성한다.
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [54]:
c.transpose((1, 2, 0)) # 깊이->열/행->깊이/열->행

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [55]:
np.transpose(c, (1, 2, 0)) #위의 결과와 동일

array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]]])

In [56]:
np.transpose(c)

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

### np.swapaxes()

In [61]:
x = np.array([[7, 8, 9]])
x

array([[7, 8, 9]])

In [63]:
y = np.swapaxes(x, 0, 1) # swapaxes()를 통해 0축과 1축이 교환된 배열 뷰가 반환된다.
y

array([[7],
       [8],
       [9]])

In [64]:
y[0, 0] = 10 # 다음 코드로 뷰의 위치를 수정하면 원본 배열에도 반영이된다.
x

array([[10,  8,  9]])

In [65]:
x = np.array(np.arange(8).reshape(2, 2, 2))
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [66]:
np.swapaxes(x, 0, 2) #배열x의 축0과 축2를 서로 바꾼 뷰를 반환한다.

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [67]:
np.transpose(x, (2, 1, 0)) #위의 결과와 동일

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

## 복사(copy)와 보기(뷰, view)

### 보기(view)

In [68]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [69]:
v = org.view() # ndarray.view()로 org와 동일한 저장소의 보기가 표시될 수 있다.
v

array([0, 1, 2, 3, 4])

In [72]:
v[2] = 200 # 다음 코드로 뷰를 수정하면, 원본인 org에도 반영이 된다. 보기는 이러한 수정에 주의해야한다.
print(v, org)

[  0   1 200   3   4] [  0   1 200   3   4]


### 복사(copy)

In [73]:
org = np.arange(5)
org

array([0, 1, 2, 3, 4])

In [74]:
c = org.copy() # ndarray.copy()를 통해 복사된 새로운 배열 c가 생성된다.
c

array([0, 1, 2, 3, 4])

In [75]:
c[2] = 200
c

array([  0,   1, 200,   3,   4])

In [76]:
org # view와 다르게 c는 새로 생성된 배열이므로 원본 org에는 수정된 내용이 적용되지 않는다.

array([0, 1, 2, 3, 4])

### 배열이 뷰인지 복사본인지 확인하는 방법

In [94]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [78]:
y = x.reshape(2, 3) # view를 반환/ reshape를 통해 다른형상으로 반환하는것도 view이다.
y

array([[0, 1, 2],
       [3, 4, 5]])

In [79]:
y.base # 뷰의 base 속성은 원본 배열을 반환한다.

array([0, 1, 2, 3, 4, 5])

In [80]:
z = y.transpose() # 전치행렬을 저장한 코드도 뷰인 것을 알 수 있다.
z.base

array([0, 1, 2, 3, 4, 5])

In [81]:
c = z.copy() # z.copy()로 새로운 복사본을 저장한 변수 c의 속성 base는 None이다.
print(c.base)

None


### ndarray의 보기로 같은 구조만 수정 가능

In [82]:
lst = list(range(8))
lst

[0, 1, 2, 3, 4, 5, 6, 7]

In [83]:
lst[3:5] = [30, 40, 50]
lst

[0, 1, 2, 30, 40, 50, 5, 6, 7]

In [84]:
x = np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [85]:
x[3:5] = [30, 40]
x

array([ 0,  1,  2, 30, 40,  5,  6,  7])

In [86]:
x[3:5] = [30, 40, 50] # 첨자와 원소의 개수가 다르면 오류가 발생한다.
x

ValueError: could not broadcast input array from shape (3,) into shape (2,)

## 보기(뷰, view)와 얕은 복사

### 얕은 복사(shallow copy)

In [87]:
a = np.array([[1, 2, 3], [4, 5, 6]]) # 변수 a는 모양 (2, 3)의 2차원 배열이다.
a

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
b = a # ndarray의 일반 대입은 단지 얕은 복사로서 변수 이름이 같은 배열을 참조한다. 그러므로 is 연산 결과가 True이다.
b is a

True

In [89]:
print(id(a))
print(id(b)) # 다음과 같이 함수의 id가 같다.

132873448501968
132873448501968


In [90]:
print(b.base) # 배열 b도 a와 같으므로 b.base는 None을 반환한다.

None


In [95]:
b[0, 0] = 100 # 배열 b는 a와 같으므로 b를 수정해도 a가 수정된다.
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [96]:
v = a.reshape(3, 2) # reshape(3, 2)로는 view가 만들어진다.
v

array([[100,   2],
       [  3,   4],
       [  5,   6]])

In [97]:
print(id(a)) #보기는 얕은 복사와 달리 원본과 메모리주소가 다르다.
print(id(v))

132873448501968
132873448649328


In [98]:
v[0, 1] = 200 # view는 원본에도 바로 적용되므로 v를 수정하면 원본 a도 수정된다.
a

array([[100, 200,   3],
       [  4,   5,   6]])

In [99]:
v.base # v는 보기이므로 v.base가 배열로 표시된다.

array([[100, 200,   3],
       [  4,   5,   6]])

# *SECTION 06*

## 브로드캐스팅 개요와 간단 연산

### 브로드캐스팅 개요

In [103]:
from numpy import array

a = array([3, 4, 5])
b = array([8, 7, 6])

a + b

array([11, 11, 11])

In [104]:
from numpy import array

a = array([3, 4, 5, 7])
b = array([8, 7 ,6])
a * b # 두 배열의 모양이 애매하게 다르면 오류가 발생한다.

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

### 스칼라 또는 단일 값과 배열의 연산

In [105]:
from numpy import array

a = array([3, 4, 5])
a

array([3, 4, 5])

In [106]:
b = 2
b

2

In [107]:
a + b # 내부적으로 스칼라 b가 b = [2, 2, 2]로 브로드캐스트되어 연산이 수행된다. / 즉, 브로드캐스트는 스칼라 b를 배열 a와 같은 모양의 배열이 되도록 늘리는 작업이다.

array([5, 6, 7])

In [108]:
A = array([[1, 2, 3], [1, 2, 3]])
A

array([[1, 2, 3],
       [1, 2, 3]])

In [110]:
A + 2 # 다음도 브로드 캐스팅된 예이다.

array([[3, 4, 5],
       [3, 4, 5]])

## 2차원 배열의 브로드캐스팅

### 하나의 배열이 1차원으로 다른 배열 열수와 같은 구조의 브로드캐스팅

In [111]:
from numpy import arange

x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
y = arange(-1, 2)
y

array([-1,  0,  1])

In [113]:
x * y # 배열 y 를 브로드캐스트해 늘리면 배열 x와 y는 모양이 (3, 3)으로 같아 산술 연산이 가능해진다.

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [114]:
x + y # 더하기 또한 잘 수행된다.

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

### 하나의 배열이 1차원으로 다른 배열 행수와  같은 구조의 브로드캐스팅

In [116]:
from numpy import arange

x = arange(1, 10).reshape(3, 3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [117]:
y = arange(3, 10, 3).reshape(3, 1)
y

array([[3],
       [6],
       [9]])

In [118]:
x / y # y가 브로드 캐스팅 되어 연산이 잘 수행된다.

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 0.83333333, 1.        ],
       [0.77777778, 0.88888889, 1.        ]])

In [120]:
x - y # 빼기도 마찬가지

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

### 행 또는 열이 1인 두 배열의 브로드캐스팅

In [127]:
from numpy import arange

x = arange(1, 4)
x

array([1, 2, 3])

In [128]:
 y = arange(1, 4).reshape(3, 1)
 y

array([[1],
       [2],
       [3]])

In [125]:
x * y # x와 y 모두 브로드캐스팅된다.

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [130]:
x / y # 다음은 나누기를 수행한다.

array([[1.        , 2.        , 3.        ],
       [0.5       , 1.        , 1.5       ],
       [0.33333333, 0.66666667, 1.        ]])

In [131]:
x = arange(0, 10, 3).reshape(4, 1) # 0, 3, 6, 9를 4행 1의 배열로 반환
x

array([[0],
       [3],
       [6],
       [9]])

In [132]:
y = arange(1, 3)
y

array([1, 2])

In [133]:
x * y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [134]:
x + y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

### 상수 np.newaxis 활용해 두 배열의 브로드캐스팅

In [1]:
import numpy as np
from numpy import array

x = array([0, 10, 20, 30]) # (4,)의 1차원 배열 x
x

array([ 0, 10, 20, 30])

In [2]:
a = x[None, :] # None은 np.newaxis와 같다. 2차원으로 차원이 증가함.
a

array([[ 0, 10, 20, 30]])

In [3]:
a = x[np.newaxis, :] # 마찬가지로 None을 상수인 np.newaxis로 바꿔도 차원이 증가한다.
a

array([[ 0, 10, 20, 30]])

In [4]:
a = x[:, np.newaxis] # 반대로 np.newaxis를 뒤에 작성하면 열이 추가된다.
a

array([[ 0],
       [10],
       [20],
       [30]])

In [7]:
from numpy import array

b = array([1, 2, 3]) # b는 모양 (3, )인 1차원 배열이다.
b

array([1, 2, 3])

In [8]:
a + b # 브로드캐스팅 되어 자동으로 연산된다.

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [10]:
a * b

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

# *SECTION07*



## 고급색인

### 1차원 배열의 색인

In [11]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
print(x[1])
print(x[:5])

1
[0 1 2 3 4]


In [14]:
print(x[[2]]) #ndarray에서 정수배열 인덱싱을 사용하면 배열에서 여러 임의 항목을 선택할 수 있다.
print(x[[2, 3]])

[2]
[2 3]


In [15]:
x[[2, 3, 5, 8]]

array([2, 3, 5, 8])

In [16]:
x[np.array([5, 3, -4, 8])] #인덱스로 ndarray '배열'도 가능하다.

array([5, 3, 6, 8])

In [17]:
x[np.array([10])] # 범위벗어날시 오류발생

IndexError: index 10 is out of bounds for axis 0 with size 10

### 2차원 배열의 색인

In [16]:
import numpy as np
from numpy import arange

x = arange(56).reshape(7, 8) # 0~55까지의 숫자를 7행 8열 배열로 출력한다.
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [2]:
x[0, 1] # 배열 x의 0행 1열에 있는 인자를 출력.

1

In [3]:
x[:, 2:8] # x의 모든행에서 2열부터 7열까지 출력한다.

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [4]:
x[[0], [1]] # x의 0축의 인덱스0, 1축의 인덱스 1을 출력.

array([1])

In [5]:
x[:, [5, 4]] # x의 0축에 모두 해당하고 5열과 4열을 순서대로 출력한다.

array([[ 5,  4],
       [13, 12],
       [21, 20],
       [29, 28],
       [37, 36],
       [45, 44],
       [53, 52]])

In [6]:
x[[1, 3]] # x의 1행과 2행을 2차원 배열로 출력한다.

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [7]:
x[[1, 3], :] # x의 1행과 2행을 출력하고, 열은 전체로 인식한다.

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [8]:
x[[1, 3], [2, 2]] # 0축과 1축의 "배열의 수"가 같으면 각각 대응되는 순서대로 첨자에 해당되는 각각의 인자를 출력한다.

array([10, 26])

In [9]:
x[[1, 3], [2]] # 배열의 인자 수가 맞지 않을경우 [2]가 브로드캐스팅되어 [2, 2]가 된다.

array([10, 26])

In [10]:
x[[1, 3], [3, 3]] # 1행 3열, 3행 3열의 인자를 출력한다.

array([11, 27])

In [11]:
x[[1, 3], [3]] # 배열의 인자 수가 맞지 않을경우 [3]이 브로드캐스팅되어 [3, 3]이 된다.

array([11, 27])

In [12]:
from numpy import array #같은 차원에서 인자의 수가 다른경우는 브로드캐스팅이 불가능하다.
x[array([0, 2, 4], array([0, 1]))]

TypeError: Cannot construct a dtype from an array

In [17]:
x[np.array([0, 2, 4]), 1] # 브로드캐스팅되어 [0, 1], [2, 1], [4, 1]에 해당하는 인자들로 구성된 모양 (3, )의 1차원 배열이 반환된다.

array([ 1, 17, 33])

In [18]:
print(x[0, 1])
print(x[2, 1])
print(x[4, 1])

1
17
33


## 다양한 모양의 배열 색인

### 기본 색인 방법

In [19]:
from numpy import arange

a = arange(40).reshape(5, 8) # 0 ~ 39를 5행 8열로 출력.
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [20]:
a[2:4, 3:7] #a의 2-3행, 3-6열에 해당하는 인자를 2차원 배열로 출력

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

### 고급 색인 방법

In [21]:
a[arange(2, 4)] # 2행과 3행으로 구성된 배열을 반환

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [25]:
a[arange(2, 4)][:, [1, 0]] # 위의 2,3행에서 1열과 0열을 차례로 출력한다.

array([[17, 16],
       [25, 24]])

In [27]:
a[arange(2, 5)][:, [1, 0, 3, 5]] # 2행, 3행. 4행에서 1,0,3,5열을 차례로 출력.

array([[17, 16, 19, 21],
       [25, 24, 27, 29],
       [33, 32, 35, 37]])

In [28]:
a[arange(2, 5)][:, arange(-1, -8, -1)] # 음수첨자로도 열을 지정할 수 있다.

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])

# *END OF CODE*