<a href="https://colab.research.google.com/github/bengaldr0gon/2024-intro-DA-code/blob/main/CHAPTER_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# *SECTION01*

## 배열 결합 개요와 기본 함수

### 배열 결합 개요

### numpy.vstack()

In [1]:
import numpy as np

a = np.arange(6).reshape(3, 2) # 0~5까지의 3행 2열 배열
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [3]:
b = np.arange(6, 12).reshape(3, 2) # 6~11까지의 3행 2열 배열
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [4]:
np.vstack((a, b)) # a, b 배열을 세로로 쌓는다.

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [5]:
np.vstack((b, a)) # 앞에오는게 위로 감을 알 수 있음.

array([[ 6,  7],
       [ 8,  9],
       [10, 11],
       [ 0,  1],
       [ 2,  3],
       [ 4,  5]])

In [7]:
c = np.arange(20, 24).reshape(2, 2) # 20~23까지의 2행 2열 배열을 출력,
c

array([[20, 21],
       [22, 23]])

In [8]:
np.vstack((a, c)) # a, c 배열을 세로로 쌓는다.

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [20, 21],
       [22, 23]])

In [9]:
np.vstack((a, b, c)) # 열이 모두 2개인 배열 a, b, c를 함께 수직으로 합칠 수 있다.

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [20, 21],
       [22, 23]])

In [10]:
d = np.array([100, 200])
np.vstack((a, d)) # 차수가 첫 축을 제외한 나머지 축의 모양이 같으면 수직으로 합칠 수 있다.

array([[  0,   1],
       [  2,   3],
       [  4,   5],
       [100, 200]])

In [11]:
d = np.array([100, 200, 300]) #다음과 같이 (2, 2)인 배열a와 원소가 3개인 1차원 배열d는 수직으로 합칠 수 없다.
np.vstack((a, d))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [12]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([5, 6, 7])
np.vstack((x, y)) # 즉, 수직으로 합치는 경우 가로길이(열 수)가 같아야한다.

array([[1, 2, 3],
       [5, 6, 7]])

### numpy.hstack()

In [13]:
import numpy as np

a = np.arange(6).reshape(3, 2) # 0~5까지의 3행 2열 배열
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [14]:
b = np.arange(10, 19).reshape(3, 3) # 10~18까지의 3행 3열 배열
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [15]:
np.hstack((a, b)) # a, b 배열을 가로로 쌓는다.

array([[ 0,  1, 10, 11, 12],
       [ 2,  3, 13, 14, 15],
       [ 4,  5, 16, 17, 18]])

In [17]:
c = np.array([[10, 20], [30, 40]]) # 2행 2열 배열을 출력
c

array([[10, 20],
       [30, 40]])

In [18]:
np.hstack((a, c)) #배열 a는 (3,2)형태의 배열, 배열 c는 (2,2)형태의 배열로, 행의 개수(높이)가 다르므로, 배열을 가로로 합칠 시 오류가 발생한다.

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [20]:
np.hstack((np.arange(3), np.arange(10, 15))) #1차원 배열은 원소 수에 상관없이 무조건 수평으로 합칠 수 있다.

array([ 0,  1,  2, 10, 11, 12, 13, 14])

## 결합 연산 column_stack()과 row_stack()

### numpy,column_stack()

In [21]:
import numpy as np

a = np.arange(6).reshape(3, 2) # 3행2열의 배열을 출력.
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [22]:
b = np.arange(10, 22).reshape(3, 4) # 3행 4열의 배열을 출력.
b

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [23]:
np.column_stack((a, b)) # 2차원 배열 a, b를 수평으로 열로 합친다.

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [25]:
np.hstack((a, b)) # np.column_stack() 은 np.hstack()과 같은기능을 한다.

array([[ 0,  1, 10, 11, 12, 13],
       [ 2,  3, 14, 15, 16, 17],
       [ 4,  5, 18, 19, 20, 21]])

In [26]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x, y)) # 독특하게 1차원 배열에서는 각각 축을 1로 확장하고 열로 쌓아 만든 2차원 배열을 반환한다.

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [27]:
x[:, np.newaxis] # newaxis를 통해 축을 하나 증가시킨다.

array([[1],
       [2],
       [3]])

In [28]:
y[:, np.newaxis] # newaxis를 통해 축을 하나 증가시킨다.

array([[10],
       [20],
       [30]])

In [29]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])
np.column_stack((x[:, np.newaxis], y[:, np.newaxis])) # 다음과 같이 np.column_stack(x, y)의 결과와 같은 결과를 얻는것을 알 수 있다.

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30]])

In [31]:
np.hstack((x, y)) # 그러나 np.hstack()의 경우는 np.column_stack()의 결과와 전혀 다르다,

array([ 1,  2,  3, 10, 20, 30])

In [33]:
np.column_stack == np.hstack # np.column_stack()과 np.hstack()의 결과가 항상 같은것은 아니므로 다음도 False가 출력된다.

False

### numpy.concatenate()

In [36]:
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6]) # a, b, c는 각각 모양이 (2, )인 1차원 배열

In [39]:
np.concatenate((a, b, c)) # a, b, c가 1차원 배열이므로 축 0을 중심으로 가로로 추가된다.

array([1, 2, 3, 4, 5, 6])

In [40]:
np.concatenate((a, b, c), axis = 0) # axis = 0을 기술해도 결과는 같다.

array([1, 2, 3, 4, 5, 6])

In [41]:
np.concatenate((a, b, c), axis = None) # axis = 0인 축이 None인 것으로 지정할 수 있다.(평면화)

array([1, 2, 3, 4, 5, 6])

In [42]:
import numpy as np

x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [43]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [45]:
z = np.arange(20, 24).reshape(2, 2)
z

array([[20, 21],
       [22, 23]])

In [46]:
np.concatenate((x, y)) # 다음 코드로 축 0을 기준으로 합칠 수 있다. 즉, 열 수가 같으면 수직으로 합칠 수 있다.

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [48]:
np.concatenate((x, y, z)) # 그러나 모양(2, 2)로 열 수가 다른 z는 수직으로 합칠 수 없다.

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 2 has size 2

In [49]:
np.concatenate((x, y), axis = 1) # 다음 코드로는 축 1을 중심으로 합쳐지므로 수평으로 합쳐진다.

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [53]:
np.concatenate((x, y, z), axis = 1) # x, y, z가 모두 행수가 2이므로 다음과 같은 결과가 나온다.

array([[ 0,  1,  2, 10, 11, 12, 20, 21],
       [ 3,  4,  5, 13, 14, 15, 22, 23]])

In [54]:
np.concatenate((x, y), axis = None) # axis = None으로 지정하면, 배열 사용전에 모두 평면화(1차원화) 되어 연산된다.

array([ 0,  1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 15])

### numpy.stack()

In [55]:
import numpy as np

a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [56]:
b = np.array([4, 5, 6])
b

array([4, 5, 6])

In [57]:
np.stack((a, b)) # np.stack() 함수는 주어진 배열을 합쳐 하나의 배열로 만든다(차원 증가)

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
np.stack((a, b), axis = 1) # axis = 1로 수평으로 2차원 배열을 만든다.

array([[1, 4],
       [2, 5],
       [3, 6]])

In [61]:
np.stack((a, b), axis = -1) # axis = -1로 지정해도 결과는 같다. -1은 마지막 축을 의미한다.

array([[1, 4],
       [2, 5],
       [3, 6]])

In [63]:
x = np.arange(6).reshape(2, 3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [65]:
y = np.arange(10, 16).reshape(2, 3)
y

array([[10, 11, 12],
       [13, 14, 15]])

In [67]:
z = np.arange(20, 26).reshape(2, 3)
z

array([[20, 21, 22],
       [23, 24, 25]])

In [68]:
ax0 = np.stack((x, y, z), axis = 0) #np,stack()으로 배열 x, y, z를 축 0방향으로 합치는 코드. 3차원 배열이 생성됨.(각각의 배열로 하나의 "깊이"를 만든다고 생각하자.)
ax0

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]]])

In [69]:
ax0.shape # 깊이3, 행2, 열3

(3, 2, 3)

In [70]:
ax1 = np.stack((x, y, z), axis = 1) # 배열 x, y, z를 축 1 방향으로 합치는 코드 (각각의 배열의 같은 첨자에 해당하는 행끼리 합쳐 하나의 깊이를 만든다.)
ax1

array([[[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22]],

       [[ 3,  4,  5],
        [13, 14, 15],
        [23, 24, 25]]])

In [71]:
ax1.shape # 깊이2, 행3, 열3

(2, 3, 3)

In [72]:
ax2 = np.stack((x, y, z), axis = 2) #각각의 배열의 같은 첨자의 행을 축2(세로)방향으로 합쳐 하나의 깊이를 생성한다.
ax2

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

In [73]:
ax2.shape # 깊이2, 행3, 열3

(2, 3, 3)

In [74]:
x

array([[0, 1, 2],
       [3, 4, 5]])

In [76]:
x[:, :, np.newaxis] #x를 마지막 축 2로 확장한 3차원 배열

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [78]:
np.expand_dims(x, axis = 2) # np.expand_dims()로도 확장한 3차원 배열을 얻을 수 있다.

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [79]:
y

array([[10, 11, 12],
       [13, 14, 15]])

In [80]:
y[:, :, np.newaxis] # y를 축 2로 확장한 3차원 배열

array([[[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]]])

In [81]:
z

array([[20, 21, 22],
       [23, 24, 25]])

In [82]:
np.expand_dims(z, axis = 2) # z를 축2로 확장한 3차원 배열

array([[[20],
        [21],
        [22]],

       [[23],
        [24],
        [25]]])

In [84]:
np.stack((x, y, z), axis = 2) # 3차원으로 확장한 x, y, z를 결합한것과 같은결과

array([[[ 0, 10, 20],
        [ 1, 11, 21],
        [ 2, 12, 22]],

       [[ 3, 13, 23],
        [ 4, 14, 24],
        [ 5, 15, 25]]])

## 배열의 결합 비교

### column_stack()과 hstack()

In [85]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [87]:
c = np.arange(1, 6, 2)
c

array([1, 3, 5])

In [88]:
c[:, np.newaxis]

array([[1],
       [3],
       [5]])

In [90]:
np.hstack((a, c[:, np.newaxis])) # 가로로 합쳐진 것을 알 수 있음

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [92]:
np.hstack((a, c)) # 다음과 같이 1차원 배열을 바로 합칠 수 없고 차원을 맞춘 후에 결합해야한다.

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [97]:
np.hstack((a, np.expand_dims(c, axis = 1))) #차수를 늘리는 방법은 마지막 차원의 수를 입력

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [98]:
np.column_stack((a, c)) # 복기하자, column_stack은 hstack과 다르게 차원을 추가하지않더라도 자동으로 추가하여 결합시킬 수 있다.

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

### row_stack()과 vstack()

In [99]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [100]:
b = np.arange(1, 5)
b

array([1, 2, 3, 4])

In [102]:
np.row_stack((a, b)) # 배열 a와 b를 세로로 합친다.

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [104]:
np.vstack((a, b)) # 배열 a와 b를 세로로 합친다. row_stack과 vstack은 완전히 같은 함수

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

### np.c_[]와 np.column_stack()

In [118]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [107]:
np.c_[a, b] # 배열 a와 b를 2차원 배열로 늘려 수평으로 합친결과를 반환

array([[1, 4],
       [2, 5],
       [3, 6]])

In [109]:
np.column_stack((a, b)) # column_stack도 마찬가지이다.

array([[1, 4],
       [2, 5],
       [3, 6]])

In [110]:
x = np.array([[1, 2, 3]])
y = np.array([[4, 5, 6]])

In [111]:
np.c_[x, y] # x 와 y가 각각 2차원 배열이기에 수평으로(축 1을 기준으로) 합친 2차원 배열을 출력한다.

array([[1, 2, 3, 4, 5, 6]])

In [114]:
np.column_stack((x, y))  # column_stack도 마찬가지

array([[1, 2, 3, 4, 5, 6]])

In [115]:
np.c_[x, 10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [123]:
np.column_stack([x, 10, 20, y]) #np.c_[]와 결과가 같다.

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

## np.r[]

### np.r[] 개요

In [124]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [125]:
np.r_[a, b] # 1차원 배열 a와 b를 수평으로 합칠 수 있다.

array([1, 2, 3, 4, 5, 6])

In [126]:
np.hstack((a, b)) # 마찬가지로 가로로 합침.

array([1, 2, 3, 4, 5, 6])

In [128]:
np.row_stack((a, b)) #row_stack은 배열을 세로로 합친다.

array([[1, 2, 3],
       [4, 5, 6]])

In [130]:
np.r_[a, 0, 0, b]

array([1, 2, 3, 0, 0, 4, 5, 6])

In [132]:
np.r_[3:10:3, [0]*2, 5, 6] # 여기서 3:10:3은 arange의 옵션 start, stop, step 을 의미한다.

array([3, 6, 9, 0, 0, 5, 6])

In [134]:
np.r_[-1:1:6j, [0]*2, 5, 6] # 여기서 6j는 6개의 값을 생성하라는 것이며, 시퀀스[-1, -0.6, -0.2, 0.2, 0.6, 1]을 의미한다.

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ,  0. ,  0. ,  5. ,  6. ])

In [136]:
np.linspace(-1, 1, 6) # 배열로도 생성 가능하다.

array([-1. , -0.6, -0.2,  0.2,  0.6,  1. ])

### np.r_[i, j, k', a, b]

In [137]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [138]:
np.r_[a, a, a] #a를 축 0방향으로 3번 쌓는다.

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [140]:
np.r_['0', a, a] # np.r_['0', ...] 처럼 첫 인자는 정수 문자열이 위치할 수 있다. 첫 정수는 합쳐지는 축을 지정한다.

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [141]:
np.r_['-1', a, a] # 첫 정수가 -1일 경우 마지막 축인 1로 합친 결과를 얻는다.

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [142]:
np.r_['1', a, a] # 첫 정수가 1일 경우에도 이 경우에는 같은 결과를 얻는다,

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [144]:
np.r_['0, 2', [1,2,3], [4,5,6]] # 두번째 인자는 확장할 차원을 의미하고, 첫번째 인자를 축으로 합친다.

array([[1, 2, 3],
       [4, 5, 6]])

In [145]:
np.r_['0, 3', [1,2,3], [4,5,6]] #첫번째 인자를 축으로 합친 후에 차원이 맞지않을경우 차원을 확장한다.

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [146]:
np.r_['0, 3, 0', [1, 2, 3], [4, 5, 6]] # 세번째 인자는 확장 방법에 관련되어있다. 세번쨰 인자가 0일경우 각각(3, 1, 1)로 확장됨.

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [148]:
np.r_['0, 3, 0', [1, 2, 3], [4, 5, 6]].shape # 최종적으로 (6, 1, 1)로 확장됨을 알 수있음.

(6, 1, 1)

In [150]:
np.r_['0, 3, 1', [1, 2, 3], [4, 5, 6]] # 1인 경우에는 (1, 3, 1)로 확장되고

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [153]:
np.r_['0, 3, 1', [1, 2, 3], [4, 5, 6]].shape # 최종적으로 (2, 3, 1)로 확장됨.

(2, 3, 1)

In [154]:
np.r_['0, 3, 2', [1, 2, 3], [4, 5, 6]] # 2인 경우에는 (1,1,3)으로 확장되고, 최종적으로 2, 1, 3으로 확장된다.

array([[[1, 2, 3]],

       [[4, 5, 6]]])

## 1차원 배열, 벡터의 다양한 결합 방법

### 여러 1차원 배열을 수평 방향으로 합치는 방법

In [155]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a.shape)
print(b.shape)

(3,)
(3,)


In [156]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [158]:
np.r_[a, b] # 수평으로 합치는 것은 np.r_[]로 가능하다.

array([1, 2, 3, 4, 5, 6])

In [160]:
np.concatenate((a, b)) # np.concatenate()도 가능하다.

array([1, 2, 3, 4, 5, 6])

### 여러 1차원 배열을 수직 방향으로 합치는 방법

In [161]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a.shape)
print(b.shape)

(3,)
(3,)


In [162]:
np.vstack((a, b)) # 세로로 합침

array([[1, 2, 3],
       [4, 5, 6]])

In [163]:
np.row_stack((a, b)) # row_stack으로도 가능함.

array([[1, 2, 3],
       [4, 5, 6]])

In [164]:
np.r_[a[np.newaxis, :], b[np.newaxis, :]] # np.newaxis를 앞에 추가하면 행을추가한다.

array([[1, 2, 3],
       [4, 5, 6]])

In [166]:
np.concatenate((a[np.newaxis, :], b[np.newaxis, :])) #concatenate도 가능하다.

array([[1, 2, 3],
       [4, 5, 6]])

### 여러 1차원 배열을 행으로 확장해 수평 방향으로 합치는 방법

In [186]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a.shape)
print(b.shape)

(3,)
(3,)


In [169]:
np.column_stack((a, b)) #column_stack은 1차원은 2차원으로 확장해 결합시킨다,

array([[1, 4],
       [2, 5],
       [3, 6]])

In [170]:
np.hstack((a[:, np.newaxis], b[:, np.newaxis])) # np.newaxis을 뒤에 쓰면 열을 추가한다.

array([[1, 4],
       [2, 5],
       [3, 6]])

In [182]:
np.c_[a, b] #c_를 통해서도 가능하다.

array([[1, 4],
       [2, 5],
       [3, 6]])

In [188]:
np.concatenate(((a[:, np.newaxis], b[:, np.newaxis])), axis = 1)  # 축1을 기준으로 concatenate를 사용해서도 결합가능하다.

array([[1, 4],
       [2, 5],
       [3, 6]])

# *SECTION02*

## 기본 함수 split()

### np.split(ary, n))

In [189]:
import numpy as np

x = np.arange(9.0) # 실수 9개로 구성된 배열 x를 출력
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [191]:
s = np.split(x, 3) #배열 x를 3개로 분할하고, 나누어진 각각의 배열을 항목으로 하는 배열을 출력한다.
s

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [192]:
print(type(s))
print(s[0])

<class 'list'>
[0. 1. 2.]


In [193]:
np.split(x, 4) # 4로 나눌경우 동등하게 떨어지지 않아 오류가 발생한다.

ValueError: array split does not result in an equal division

### np.split(ary, [i, j, k, ...])

In [194]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [195]:
np.split(x, [2, 6]) # x를  순서대로 원소가 2개, 4개 3개인 배열로 분리 할 수 있다. a[:2], a[2:6], a[6:]으로 나눔.

[array([1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [196]:
y = np.arange(10, 61, 10)
y

array([10, 20, 30, 40, 50, 60])

In [198]:
np.split(y, [2, 3, 4]) #인덱스 [2]앞에서 한번, [3]앞에서 한번, [4]앞에서 한번 끊어서 총 4개의 배열을 출력한다.

[array([10, 20]), array([30]), array([40]), array([50, 60])]

In [200]:
np.split(y, [2, 3, 4, 6]) # 첨자가 5까지 작성가능하므로 6은 빈 배열이 출력된다.

[array([10, 20]),
 array([30]),
 array([40]),
 array([50, 60]),
 array([], dtype=int64)]

In [201]:
y[4:6]

array([50, 60])

In [202]:
y[6:]

array([], dtype=int64)

### 다차원 배열 np,hsplit(ary, n)

In [205]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [207]:
np.split(a, 3, axis = 1) # a를 축1방향으로 이동하며 3개로 분리한다.

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [209]:
np.split(a, 4, axis = 1) # 4개로 분리하면 다음과 같음

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

In [211]:
np.split(a, 5, axis = 1) # 5개로 분리하면 동등하게 떨어지지 않아 오류가 발생한다.

ValueError: array split does not result in an equal division

In [213]:
np.split(a, [3, 5, 7], axis = 1) # 축 1으로 기준으로 슬라이싱을 통해 3, 5, 7 열 앞에서 분리한다.

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8,  9, 10, 11],
        [19, 20, 21, 22, 23]])]

In [214]:
b = np.arange(24).reshape(6, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [215]:
np.split(b, 3, axis = 0) # b를 축0방향으로 3등분한 결과이다.

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [216]:
np.split(b, [2, 4, 6], axis = 0) # 5까지 첨자로 지정가능하기 때문에 6은 빈 배열이 출력된다.

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([], shape=(0, 4), dtype=int64)]

## 분할 함수 hsplit()과 vsplit()

### np.hsplit(ary)

In [217]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [220]:
np.hsplit(a, 2) # a를 2등분

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [224]:
np.hsplit(a, [2, 5]) # 2, 5에서 한번씩 끊어 3개의 슬라이싱 배열로 분할한다.

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7, 8, 9])]

In [225]:
a = np.arange(24).reshape(2, 12)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [226]:
np.hsplit(a, 3) #a를 축1을 기준으로 3등분하여 4열로 구성된 배열을 출력한다.

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]),
 array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [227]:
np.hsplit(a, 4) # 배열 a를 축 1방향으로 4개로 분리하면 3열로 구성된 배열을 출력한다.

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [15, 16, 17]]),
 array([[ 6,  7,  8],
        [18, 19, 20]]),
 array([[ 9, 10, 11],
        [21, 22, 23]])]

In [228]:
np.hsplit(a, 5) # 5는 짝이 맞지않음으로 오류가 발생한다. 계산할때는 열의 개수/분리개수 로 계산한다.

ValueError: array split does not result in an equal division

In [230]:
np.hsplit(a, (3, 5, 8)) # a[:,:3], a[:,3:5], a[:, 5:8], a[:, :8]로 분리되어 출력한다.

[array([[ 0,  1,  2],
        [12, 13, 14]]),
 array([[ 3,  4],
        [15, 16]]),
 array([[ 5,  6,  7],
        [17, 18, 19]]),
 array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

In [232]:
a[:, :3] # 위의 결과의 첫 항목과 같다.

array([[ 0,  1,  2],
       [12, 13, 14]])

In [233]:
a[:, :8] # 위의 결과의 마지막 항목과 같다.

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [12, 13, 14, 15, 16, 17, 18, 19]])

### np.vsplit(ary)

In [234]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [235]:
np.vsplit(a, 2) # 수직분할은 2차원이상의 배열만 가능하므로 오류가 발생한다,

ValueError: vsplit only works on arrays of 2 or more dimensions

In [237]:
a = np.arange(18).reshape(6, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [239]:
np.vsplit(a, 3) # 축 0을 기준으로 3등분한다.

[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [241]:
np.vsplit(a, 4) # 축 0을 기준으로 4등분한다. 전체 행은 6행이므로 6/4는 0으로 나누어 떨어지지않아 오류가 발생한다.

ValueError: array split does not result in an equal division

In [243]:
np.vsplit(a, (1, 4, 6)) # 첨자 1, 4, 6 앞에서 끊어 각각 배열 4개를 출력한다.

[array([[0, 1, 2]]),
 array([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]]),
 array([], shape=(0, 3), dtype=int64)]

In [244]:
a[:1, :] # 위 결과의 첫 항목과 같다

array([[0, 1, 2]])

In [246]:
a[4:6, :] # 위 결과의 세 번째 항목과 같다

array([[12, 13, 14],
       [15, 16, 17]])

In [247]:
a[6:, :]  # 위 결과의 마지막 항목과 같다.

array([], shape=(0, 3), dtype=int64)